[platformio]
src_dir = src
include_dir = include

[env:esp32-s3-devkitc-1]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino

; Mantém duas áreas de firmware para atualização OTA
board_build.partitions = partitions.csv

; Configuração de memória para a placa ESP32-S3 16MB/8MB PSRAM
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

monitor_speed = 115200

; Força o LDF a ignorar dependências não utilizadas
lib_ldf_mode = chain
lib_compat_mode = strict

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DBOARD_HAS_PSRAM
    -Iinclude

; Remove explicitamente a pasta SD_MMC da lista de compilação do framework
build_src_filter = +<*> -<.git/> -<.svn/> -<../lib/SD_MMC/>

lib_deps =
    lovyan03/LovyanGFX@1.2.27
    tzapu/WiFiManager@2.0.17
    lvgl/lvgl@8.3.11
    bitbank2/AnimatedGIF@2.2.0