name: Compilar Firmware ESP32-S3

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Instalar Placa ESP32
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Instalar Bibliotecas Necessárias
        run: |
          arduino-cli lib install "LovyanGFX"

      - name: Compilar Projeto Arduino
        run: |
          # Componta para a raiz do repositório onde está o HondApp.ino
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --output-dir ./build .

      - name: Salvar o Arquivo Binário gerado
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./build/HondApp.ino.bin
